### ISSUE TITLE
推理结果输出不对

### ISSUE THREAD

**Issue by Carious-ads** [Tlntin/qwen-ascend-llm#4]
我是使用OpenEuler系统，没有使用docker镜像，手动转换om模型，在推理时输出这个结果：
![image](https://github.com/user-attachments/assets/6d50f9db-5387-4852-a0c8-df38c555824a)

**Comment by Tlntin** [comment]
看报错日志，貌似是转模型的时候没有设置动态shape

**Comment by Carious-ads** [comment]
> 看报错日志，貌似是转模型的时候没有设置动态shape
这个是我的转换过程，按照你提供的转换流程进行转换
![image](https://github.com/user-attachments/assets/276cb81d-ccdc-464e-aeaa-6464578bf121)
![image](https://github.com/user-attachments/assets/530dd900-149d-4dd8-9db4-056a5825af05)

**Comment by Tlntin** [comment]
看操作没有问题，你试试onnx推理正常嘛？

**Comment by Carious-ads** [comment]
> 看操作没有问题，你试试onnx推理正常嘛？
onnx推理是正常的
![image](https://github.com/user-attachments/assets/5d84f5bb-2e4c-44dc-8085-3f07daa875ba)

**Comment by Tlntin** [comment]
那可能就是CANN的问题了，你的CANN版本是？python版本是？

**Comment by Carious-ads** [comment]
> 那可能就是CANN的问题了，你的CANN版本是？python版本是？

CANN是8.0.RC2，python是3.9

**Comment by Tlntin** [comment]
突然发现你上面的kv-cache比较长，你可以用默认的1024试试。太长了你的内存可能不够用。

**Comment by Carious-ads** [comment]
> 突然发现你上面的kv-cache比较长，你可以用默认的1024试试。太长了你的内存可能不够用。
我的内存是24G+swp16G的，我试试1024行不行

**Comment by Carious-ads** [comment]
> 突然发现你上面的kv-cache比较长，你可以用默认的1024试试。太长了你的内存可能不够用。

默认1024没有问题，感谢

**Comment by Tlntin** [comment]
不客气。

**Comment by Tlntin** [comment]
@Carious-ads 你转onnx的时候设置kv-cache-length是4096， 那么在cli_chat的时候需要加上`--max_output_length`也为4096。不加的话，会导致shape出错，所以你上面才报错了，晚点我会把这个加到readme说明一下。

**Comment by Carious-ads** [comment]
> @Carious-ads 你转onnx的时候设置kv-cache-length是4096， 那么在cli_chat的时候需要加上`--max_output_length`也为4096。不加的话，会导致shape出错，所以你上面才报错了，晚点我会把这个加到readme说明一下。

好的

**Comment by Tlntin** [comment]
新版优化了一下内存加载，目前应该可以上10k（10240）上下文了，还在测试中，没问题就会push了。
